# Generated by Django 3.1 on 2023-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
